# Generated by Django 4.0.4 on 2022-06-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_quantity_in_line_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='actual_price',
            field=models.PositiveIntegerField(help_text='Актуальная цена на данный момент.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Скидка в процентах.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Цена до скидки, создаётся атвтоматически после указания скидки.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_in_line',
            field=models.PositiveIntegerField(blank=True, help_text='Количество в линейке, создаётся атвтоматически после линейки размеров.'),
        ),
        migrations.AlterField(
            model_name='productobjects',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
