# Generated by Django 4.0.4 on 2022-06-09 11:29

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_collection_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(auto_created=True, choices=[('НОВЫЙ', 'НОВЫЙ'), ('ОФОРМЛЕН', 'ОФОРМЛЕН'), ('ОТМЕНЕН', 'ОТМЕНЕН')], default='НОВЫЙ', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('public_agreement', models.BooleanField(default=False)),
                ('lines_amount', models.PositiveIntegerField(default=0)),
                ('products_amount', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('actual_price', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AlterModelOptions(
            name='productobjects',
            options={'verbose_name': 'Отдельный товар', 'verbose_name_plural': 'Товары по отдельности'},
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productobjects')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Корзина',
            },
        ),
    ]
