# Generated by Django 4.0.4 on 2022-06-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_order_alter_productobjects_options_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_products',
            field=models.ManyToManyField(to='product.cart'),
        ),
    ]
