# Generated by Django 4.0.4 on 2022-05-25 12:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
