# Generated by Django 4.0.4 on 2022-05-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_helpqa'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurAdvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Advantage',
                'verbose_name_plural': 'Our Advantages',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='helpqa',
            options={'verbose_name': 'Q&A', 'verbose_name_plural': 'Help Q&A'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'News'},
        ),
    ]
