# Generated by Django 4.0.4 on 2022-05-26 11:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_publicoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('user_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('type_of_treatment', models.CharField(default='Callback', max_length=10)),
                ('called_status', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='n', max_length=1)),
            ],
        ),
    ]
