# Generated by Django 4.0.4 on 2022-05-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_callback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('PHONE', 'PHONE'), ('WHATSAPP', 'WHATSAPP'), ('INSTAGRAM', 'INSTAGRAM'), ('TELEGRAM', 'TELEGRAM'), ('EMAIL', 'EMAIL')], help_text='Choose from list', max_length=100)),
                ('link_to', models.CharField(max_length=255)),
            ],
        ),
    ]
