# Generated by Django 4.0.4 on 2022-05-30 04:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_socialtypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterHeaderObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo', models.ImageField(blank=True, upload_to='images/')),
                ('footer_logo', models.ImageField(blank=True, upload_to='images/')),
                ('text_info', models.TextField(blank=True)),
                ('header_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('social_type', models.ManyToManyField(to='info.socialtypes')),
            ],
        ),
    ]
