# Generated by Django 4.0.4 on 2022-06-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_footerheaderobjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHelpQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='helpqa',
            name='image',
        ),
    ]
