# Generated by Django 4.0.4 on 2022-06-14 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_imagehelpqa_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerheaderobjects',
            name='social_type',
        ),
        migrations.AddField(
            model_name='socialtypes',
            name='social_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='social_type', to='info.footerheaderobjects'),
            preserve_default=False,
        ),
    ]
