# Generated by Django 4.0.4 on 2022-06-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_remove_footerheaderobjects_social_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='type_of_treatment',
            field=models.CharField(default='Обратный звонок', max_length=20),
        ),
    ]
